INSERT INTO partymaker2.role VALUES (1, 'ROLE_ADMIN');
INSERT INTO partymaker2.role VALUES (2, 'ROLE_PARTY_MAKER');
INSERT INTO partymaker2.role VALUES (3, 'ROLE_STREET_DANCER');
INSERT INTO partymaker2.role VALUES (4, 'ROLE_SERVICE_TAX');