-- MySQL Script generated by MySQL Workbench
-- Sun 30 Oct 2016 18:59:07 EET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`role` (
  `id_role` INT NOT NULL AUTO_INCREMENT,
  `user_role` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_role`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NULL,
  `phone_number` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `billing_info` VARCHAR(45) NULL,
  `emergency_contact` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `enable` TINYINT(1) NULL DEFAULT NULL,
  `updated_date` VARCHAR(45) NULL DEFAULT NULL,
  `created_date` VARCHAR(45) NULL DEFAULT NULL,
  `id_role` INT NOT NULL,
  PRIMARY KEY (`id_user`, `id_role`),
  INDEX `fk_user_role_idx` (`id_role` ASC),
  CONSTRAINT `fk_user_role`
    FOREIGN KEY (`id_role`)
    REFERENCES `mydb`.`role` (`id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`event` (
  `id_event` INT NOT NULL AUTO_INCREMENT,
  `club_name` VARCHAR(45) NULL,
  `date` VARCHAR(45) NULL DEFAULT NULL,
  `time` VARCHAR(45) NULL DEFAULT NULL,
  `location` VARCHAR(45) NULL DEFAULT NULL,
  `club_capacity` VARCHAR(45) NULL DEFAULT NULL,
  `party_name` VARCHAR(45) NULL DEFAULT NULL,
  `zip_code` VARCHAR(45) NULL,
  PRIMARY KEY (`id_event`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_has_event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_has_event` (
  `id_user` INT NOT NULL,
  `id_role` INT NOT NULL,
  `id_event` INT NOT NULL,
  PRIMARY KEY (`id_user`, `id_role`, `id_event`),
  INDEX `fk_user_has_event_event1_idx` (`id_event` ASC),
  INDEX `fk_user_has_event_user1_idx` (`id_user` ASC, `id_role` ASC),
  CONSTRAINT `fk_user_has_event_user1`
    FOREIGN KEY (`id_user` , `id_role`)
    REFERENCES `mydb`.`user` (`id_user` , `id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_event_event1`
    FOREIGN KEY (`id_event`)
    REFERENCES `mydb`.`event` (`id_event`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table_type` (
  `id_table_type` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id_table_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table` (
  `id_table` INT NOT NULL AUTO_INCREMENT,
  `price` VARCHAR(45) NULL DEFAULT NULL,
  `available` VARCHAR(45) NULL,
  `booked` VARCHAR(45) NULL,
  `id_event` INT NOT NULL,
  `id_table_type` INT NOT NULL,
  PRIMARY KEY (`id_table`, `id_event`, `id_table_type`),
  INDEX `fk_table_event1_idx` (`id_event` ASC),
  INDEX `fk_table_table_type1_idx` (`id_table_type` ASC),
  CONSTRAINT `fk_table_event1`
    FOREIGN KEY (`id_event`)
    REFERENCES `mydb`.`event` (`id_event`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table_table_type1`
    FOREIGN KEY (`id_table_type`)
    REFERENCES `mydb`.`table_type` (`id_table_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bottle_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bottle_type` (
  `id_bottle_type` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id_bottle_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bottle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bottle` (
  `id_bottle` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `prise` VARCHAR(45) NULL DEFAULT NULL,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  `available` VARCHAR(45) NULL,
  `booked` VARCHAR(45) NULL,
  `created_date` VARCHAR(45) NULL DEFAULT NULL,
  `id_event` INT NOT NULL,
  `id_bottle_type` INT NOT NULL,
  PRIMARY KEY (`id_bottle`, `id_event`, `id_bottle_type`),
  INDEX `fk_bottle_event1_idx` (`id_event` ASC),
  INDEX `fk_bottle_bottle_type1_idx` (`id_bottle_type` ASC),
  CONSTRAINT `fk_bottle_event1`
    FOREIGN KEY (`id_event`)
    REFERENCES `mydb`.`event` (`id_event`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bottle_bottle_type1`
    FOREIGN KEY (`id_bottle_type`)
    REFERENCES `mydb`.`bottle_type` (`id_bottle_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ticket` (
  `id_ticket` INT NOT NULL AUTO_INCREMENT,
  `price` VARCHAR(45) NULL DEFAULT NULL,
  `available` VARCHAR(45) NULL,
  `booked` VARCHAR(45) NULL,
  `created_date` VARCHAR(45) NULL DEFAULT NULL,
  `id_event` INT NOT NULL,
  PRIMARY KEY (`id_ticket`, `id_event`),
  INDEX `fk_ticket_event1_idx` (`id_event` ASC),
  CONSTRAINT `fk_ticket_event1`
    FOREIGN KEY (`id_event`)
    REFERENCES `mydb`.`event` (`id_event`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`photo` (
  `id_photo` INT NOT NULL AUTO_INCREMENT,
  `photo` VARCHAR(45) NULL DEFAULT NULL,
  `id_event` INT NOT NULL,
  PRIMARY KEY (`id_photo`, `id_event`),
  INDEX `fk_photo_event1_idx` (`id_event` ASC),
  CONSTRAINT `fk_photo_event1`
    FOREIGN KEY (`id_event`)
    REFERENCES `mydb`.`event` (`id_event`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ranting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ranting` (
  `id_ranting` INT NOT NULL,
  `text` LONGTEXT NULL,
  `id_event` INT NOT NULL,
  `id_user` INT NOT NULL,
  `id_role` INT NOT NULL,
  PRIMARY KEY (`id_ranting`, `id_event`, `id_user`, `id_role`),
  INDEX `fk_ranting_event1_idx` (`id_event` ASC),
  INDEX `fk_ranting_user1_idx` (`id_user` ASC, `id_role` ASC),
  CONSTRAINT `fk_ranting_event1`
    FOREIGN KEY (`id_event`)
    REFERENCES `mydb`.`event` (`id_event`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ranting_user1`
    FOREIGN KEY (`id_user` , `id_role`)
    REFERENCES `mydb`.`user` (`id_user` , `id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
